"""create models

Revision ID: c10cf508a2e6
Revises: 
Create Date: 2023-10-20 19:32:12.394703

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c10cf508a2e6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geoname",
        sa.Column("geoname_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("asciiname", sa.String(length=200), nullable=True),
        sa.Column("alternatenames", sa.String(length=5000), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("feature_class", sa.String(length=1), nullable=True),
        sa.Column("feature_code", sa.String(length=10), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("cc2", sa.String(length=60), nullable=True),
        sa.Column("admin1_code", sa.String(length=20), nullable=True),
        sa.Column("admin2_code", sa.String(length=80), nullable=True),
        sa.Column("admin3_code", sa.String(length=20), nullable=True),
        sa.Column("admin4_code", sa.String(length=20), nullable=True),
        sa.Column("population", sa.BigInteger(), nullable=True),
        sa.Column("elevation", sa.Integer(), nullable=True),
        sa.Column("dem", sa.Integer(), nullable=True),
        sa.Column("timezone", sa.String(length=40), nullable=True),
        sa.Column("modification_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("geoname_id"),
    )
    op.create_index(
        op.f("ix_geoname_geoname_id"), "geoname", ["geoname_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geoname_geoname_id"), table_name="geoname")
    op.drop_table("geoname")
    # ### end Alembic commands ###
