version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buzz_api
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      PORT: 8000
      DATABASE_URL: mysql+mysqlconnector://admin:123@mysql:3307/buzz
      DATABASE_URL_ALEMBIC: mysql+asyncmy://admin:123@localhost:3307/buzz
      VIRTUAL_PORT: 8000
    networks:
      - buzz-network
  mysql:
    image: mysql:8.0
    container_name: mysql-8
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buzz
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - buzz-network
networks:
  buzz-network:
    driver: bridge
